#!/bin/bash

# Font setup script for Mockstars Resume Builder
echo "🎨 Setting up professional resume fonts..."

echo "📁 Font directories created in public/fonts/"
echo ""
echo "📋 Next steps to complete font setup:"
echo ""
echo "1. Download fonts from Google Fonts:"
echo "   • Inter: https://fonts.google.com/specimen/Inter"
echo "   • Roboto: https://fonts.google.com/specimen/Roboto" 
echo "   • Open Sans: https://fonts.google.com/specimen/Open+Sans"
echo "   • Lato: https://fonts.google.com/specimen/Lato"
echo "   • Source Sans Pro: https://fonts.google.com/specimen/Source+Sans+Pro"
echo ""
echo "2. Extract TTF files to these directories:"
echo "   • public/fonts/Inter/"
echo "   • public/fonts/Roboto/"
echo "   • public/fonts/OpenSans/"
echo "   • public/fonts/Lato/"
echo "   • public/fonts/SourceSansPro/"
echo ""
echo "3. Update lib/resume-fonts.ts:"
echo "   • Change 'available: false' to 'available: true' for each added font"
echo "   • Uncomment font registration code"
echo ""
echo "4. Add font loading to your app:"
echo "   • Import and call loadCustomFonts() in your app initialization"
echo ""
echo "✅ Currently available fonts:"
echo "   • Helvetica (built-in)"
echo "   • Times-Roman (built-in)"
echo "   • Helvetica-Bold (built-in)"
echo ""
echo "🎯 Target: 10 professional resume fonts total"
echo ""
echo "📖 See FONT_SETUP_GUIDE.md for detailed instructions"
